#!/usr/bin/env php
<?php

$dir = __DIR__;
$projectEnvPath = $dir . '/../../.env';
$envContent = file_get_contents($projectEnvPath);

// 备份项目的.env文件
//$envBackupPath = $dir . '/.env';
//if (file_exists($envBackupPath)) {
//    unlink($envBackupPath);
//}
//file_put_contents($envBackupPath, $envContent);

// 替换成测试配置
preg_match('/DB_DATABASE=([^\s]+)?/', $envContent, $data);
$database = $data[1];
$testEnvContent = preg_replace('/DB_DATABASE=([^\s]+)?/', 'DB_DATABASE=' . $database . '_test', $envContent);
file_put_contents($projectEnvPath, $testEnvContent);

// 执行单元测试
exec('docker exec dhyperf bash -c "
cd /hyperf-skeleton/h-mall
rm -rf runtime/container
bin/hyperf.php migrate:fresh --seed
vendor/bin/co-phpunit -c phpunit.xml --colors=always"', $output);
echo implode("\n", $output);

// 还原配置
file_put_contents($projectEnvPath, $envContent);

